project:
  type: website

website:
  title: "CTCL"
  page-footer:
    left: "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: envelope
        href: mailto:changjun.chris.lee@gmail.com
  navbar:
    right:
      - href: members.qmd
        text: Members
      - text: Activity
        href: research/working.qmd
      - text: Projects
        href: proj/index.qmd
      - text: Publications
        href: research/index.qmd

      
format:
  html:
    theme: journal
    # css: styles.css
    toc: true
    linestretch: 1.25
    langfont:
      ko: NanumMyeongjo